version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  api:
    build: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
